Adding project created for content about Building a recipe search with Elasticsearch
elastic/elasticsearch-labs pull request #350
Opened 2024-11-03 16:49 UTC by andreluiz1987

This PR contains scripts used for the article Building a recipe search with Elasticsearch

2024-11-04 13:27 UTC, carlyrichmond approved these changes

2024-11-04 14:46 UTC, carlyrichmond requested changes
I believe this should be converted to a Python notebook.

Can you check the pre-commit stage failure as well? Chatting with @JessicaGarson we want to confirm if you have setup the pre-commit stage correctly.

`python -m venv .venv
.venv/bin/pip install -qqq -r requirements-dev.txt
.venv/bin/pre-commit install`

Let us know if anything doesn't make sense!

2024-11-04 14:54 UTC, andreluiz1987 commented
> I believe this should be converted to a Python notebook.
> 
> Can you check the pre-commit stage failure as well? Chatting with @JessicaGarson we want to confirm if you have setup the pre-commit stage correctly.
> 
> `python -m venv .venv .venv/bin/pip install -qqq -r requirements-dev.txt .venv/bin/pre-commit install`
> 
> Let us know if anything doesn't make sense!

Hi Carly, I will make the corrections.

2024-11-07 10:13 UTC, carlyrichmond approved these changes

2024-11-07 10:13 UTC, merged